Repository banksystembg/BankSystem, pull requests merged in 2019-04, with the labels that each got.

#164 Update README.md
  README.md
Labels: enhancement

#166 Add bank country and money transfers total count
  src/Web/BankSystem.Web/Controllers/BankAccountsController.cs
  src/Web/BankSystem.Web/Models/BankAccount/BankAccountDetailsViewModel.cs
  src/Web/BankSystem.Web/Views/BankAccounts/Details.cshtml
Labels: enhancement

#167 Update README.md
  README.md
Labels: enhancement

#170 Add favicon
  src/Web/BankSystem.Web/wwwroot/favicon.ico
Labels: enhancement

#173 Fix 2FA key regeneration when enabling
  src/Web/BankSystem.Web/Pages/Account/Settings/Enable2fa.cshtml.cs
Labels: bug

#177 Extract payment helpers
  src/Web/Api/CentralApi/Controllers/PaymentsController.cs
  src/Web/Api/CentralApi/PaymentHelpers/DirectPaymentsHelper.cs
  src/Web/BankSystem.Web/Controllers/PaymentsController.cs
  src/Web/BankSystem.Web/PaymentHelpers/DirectPaymentsHelper.cs
Labels: enhancement

#175 Add email verification resend option
  src/Common/BankSystem.Common/EmailMessages.cs
  src/Common/BankSystem.Common/NotificationMessages.cs
  src/Services/BankSystem/BankSystem.Services/Implementations/MoneyTransferService.cs
  src/Web/BankSystem.Web/Pages/Account/ConfirmEmail.cshtml.cs
  src/Web/BankSystem.Web/Pages/Account/Login.cshtml.cs
  src/Web/BankSystem.Web/Pages/Account/Register.cshtml.cs
  src/Web/BankSystem.Web/Pages/Account/SendEmailVerification.cshtml
  src/Web/BankSystem.Web/Pages/Account/SendEmailVerification.cshtml.cs
  src/Web/BankSystem.Web/Pages/BasePage.cs
  src/Web/BankSystem.Web/Views/Shared/_Layout.cshtml
Labels: enhancement

#179 Remove validation summary
  src/Web/BankSystem.Web/Pages/Account/Register.cshtml
  src/Web/BankSystem.Web/Pages/Account/Register.cshtml.cs
  src/Web/BankSystem.Web/Pages/Account/SendEmailVerification.cshtml
  src/Web/BankSystem.Web/Startup.cs
Labels: enhancement

#180 Add unit tests for central api
  src/BankSystem.sln
  src/Tests/CentralApi.Services.Tests/CentralApi.Services.Tests.csproj
  src/Tests/CentralApi.Services.Tests/Setup/TestSetup.cs
  src/Tests/CentralApi.Services.Tests/Tests/BankServiceTests.cs
  src/Tests/CentralApi.Services.Tests/Tests/BaseTest.cs
Labels: enhancement

#183 set destination account user full name
  src/Web/BankSystem.Web/Areas/MoneyTransfers/Controllers/InternalController.cs
Labels: High priority, bug

#186 Improve payment redirect page
  src/DemoShop/DemoShop.Web/Views/DirectPayments/PaymentPostRedirect.cshtml
  src/Web/Api/CentralApi/Views/Payments/PaymentPostRedirect.cshtml
Labels: enhancement

#188 Allow purchase confirmation form resubmission after error
  src/Web/BankSystem.Web/wwwroot/source/payments/js/payments.js
Labels: enhancement

#190 Add datatables and make tables responsive
  src/Web/BankSystem.Web/Areas/Administration/Views/Accounts/Index.cshtml
  src/Web/BankSystem.Web/Areas/MoneyTransfers/Views/Home/All.cshtml
  src/Web/BankSystem.Web/Views/BankAccounts/Details.cshtml
  src/Web/BankSystem.Web/Views/Home/Index.cshtml
  src/Web/BankSystem.Web/bundleconfig.json
  src/Web/BankSystem.Web/wwwroot/source/datatables/css/datatables.css
  src/Web/BankSystem.Web/wwwroot/source/datatables/js/datatables-init.js
  src/Web/BankSystem.Web/wwwroot/source/datatables/js/datatables.js
  src/Web/BankSystem.Web/wwwroot/source/main/js/auto-datatable.js
  src/Web/BankSystem.Web/wwwroot/source/vendor/css/datatables.css
  src/Web/BankSystem.Web/wwwroot/source/vendor/js/datatables.js
Labels: enhancement

#192 Make transfer type selection page responsive
  src/Web/BankSystem.Web/Pages/MoneyTransfers.cshtml
Labels: bug

#194 Clean up code
  src/Common/BankSystem.Common/EmailMessages.cs
  src/Common/BankSystem.Common/GlobalConstants.cs
  src/Services/BankSystem/BankSystem.Services/Implementations/MoneyTransferService.cs
  src/Tests/BankSystem.Services.Tests/Setup/TestSetup.cs
  src/Tests/BankSystem.Services.Tests/Tests/BankAccountServiceTests.cs
  src/Tests/BankSystem.Services.Tests/Tests/BaseTest.cs
  src/Tests/BankSystem.Services.Tests/Tests/CardServiceTests.cs
  src/Tests/BankSystem.Services.Tests/Tests/MoneyTransferServiceTests.cs
  src/Tests/BankSystem.Services.Tests/Tests/UserServiceTests.cs
  src/Tests/CentralApi.Services.Tests/Tests/BankServiceTests.cs
  src/Tests/CentralApi.Services.Tests/Tests/BaseTest.cs
  src/Web/Api/CentralApi/Controllers/CardPaymentsController.cs
  src/Web/Api/CentralApi/Controllers/ReceiveTransactionsController.cs
  src/Web/Api/CentralApi/Infrastructure/Handlers/CustomCentralApiDelegatingHandler.cs
  src/Web/BankSystem.Web/Controllers/PaymentsController.cs
  src/Web/BankSystem.Web/Models/BankAccount/BankAccountDetailsViewModel.cs
Labels: enhancement

#198 Make replay attacks more difficult by adding timestamps
  src/Common/BankSystem.Common/Utils/Models/SignatureVerificationModel.cs
  src/Common/BankSystem.Common/Utils/SignatureVerificationUtil.cs
  src/Web/Api/CentralApi/Infrastructure/Filters/DecryptAndVerifyRequest.cs
  src/Web/Api/CentralApi/Infrastructure/Helpers/TransactionHelper.cs
  src/Web/BankSystem.Web/Infrastructure/Filters/DecryptAndVerifyRequest.cs
  src/Web/BankSystem.Web/Infrastructure/Helpers/GlobalTransferHelpers/GlobalTransferHelper.cs
Labels: bug

#207 Add unit tests for BankAccountUniqueHelper
  src/Tests/BankSystem.Services.Tests/Tests/BankAccountUniqueIdHelperTests.cs
Labels: enhancement

#206 Improve messages
  src/Common/BankSystem.Common/EmailMessages.cs
  src/Common/BankSystem.Common/NotificationMessages.cs
  src/Web/BankSystem.Web/Areas/Administration/Views/Transactions/Result.cshtml
  src/Web/BankSystem.Web/Areas/MoneyTransfers/Views/Global/Create.cshtml
  src/Web/BankSystem.Web/Pages/MoneyTransfers.cshtml
  src/Web/BankSystem.Web/Views/Shared/_Layout.cshtml
Labels: enhancement

#208 Update README.md
  README.md
Labels: enhancement

#212 Fix 2FA key null after entering an invalid password
  src/Web/BankSystem.Web/Pages/Account/Settings/Enable2fa.cshtml.cs
Labels: bug

#214 Fix password validation regex
  src/Common/BankSystem.Common/ModelConstants.cs
  src/Web/BankSystem.Web/Pages/Account/Register.cshtml.cs
  src/Web/BankSystem.Web/Pages/Account/Settings/ChangePassword.cshtml.cs
Labels: High priority, bug
